export const ROW_EDITED = 'ROW_EDITED';
export const ROW_INSERTED = 'ROW_INSERTED';
export const ROW_APPENDED = 'ROW_APPENDED';
export const ROW_DELETED = 'ROW_DELETED';
export const ROW_MOVED_UP = 'ROW_MOVED_UP';
export const ROW_MOVED_DOWN = 'ROW_MOVED_DOWN';

export const COL_SORTED_UP = 'COL_SORTED_UP';
export const COL_SORTED_DOWN = 'COL_SORTED_DOWN';

export const TEXT_IMPORTED_FROM_TABLE = 'TEXT_IMPORTED_FROM_TABLE';
export const TEXT_EXPORTED_TO_TABLE = 'TEXT_EXPORTED_TO_TABLE';
export const TEXT_IMPORTED_FROM_FILE = 'TEXT_IMPORTED_FROM_FILE';
export const TEXT_EXPORTED_TO_FILE = 'TEXT_EXPORTED_TO_FILE';

export const TEXT_EDITED = 'TEXT_EDITED';
export const TEXT_PARSE_FAILED = 'TEXT_PARSE_FAILED';